package com.los.backend.model;

/*
 * ─────────────────────────────────────────────────────────────────────────────
 * EMBEDDING vs REFERENCING decision for DecisionResult:
 *
 * WHY EMBEDDED (inside LoanApplication)?
 * ─────────────────────────────────────────────────────────────────────────────
 * DecisionResult is the BRE's verdict for THIS specific loan application.
 * It is:
 * 1. 1-to-1 with LoanApplication — one application has at most one decision result.
 * 2. Always loaded with the application — loan officers always want to see the
 *    decision alongside the application details in a single API call.
 * 3. Small (a few scalar fields + a short list of rule outcomes) — well within
 *    MongoDB's 16MB document limit.
 * 4. Never queried independently — no use case exists for "find all DecisionResults
 *    with riskScore > 80" without the parent application context.
 *
 * Note: DecisionLog (a separate @Document) stores the FULL immutable audit record.
 *       DecisionResult (embedded here) stores a lightweight SUMMARY for display.
 *       This two-layer approach keeps the LoanApplication document lean while
 *       preserving a full audit trail in its own collection.
 * ─────────────────────────────────────────────────────────────────────────────
 */

import com.los.backend.model.enums.FinalDecision;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.mongodb.core.mapping.Field;

import java.time.Instant;
import java.util.List;

/**
 * DecisionResult — a concise summary of the BRE's evaluation, embedded
 * directly inside the LoanApplication document.
 *
 * This object is null until the BRE has run (i.e., until the application
 * reaches CREDIT_CHECK status). After BRE evaluation, it is set once and
 * treated as immutable — a new loan application must be submitted to
 * trigger a fresh BRE run.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class DecisionResult {

    /**
     * finalDecision — APPROVED, REJECTED, or REVIEW.
     * This matches the LoanApplication.status transition:
     *   APPROVED  → LoanStatus.APPROVED
     *   REJECTED  → LoanStatus.REJECTED
     *   REVIEW    → stays in CREDIT_CHECK, flagged for manual override
     */
    @Field("final_decision")
    private FinalDecision finalDecision;

    /**
     * riskScore — a computed numeric risk score (0–100).
     * 0 = lowest risk (excellent profile), 100 = highest risk.
     * The BRE calculates this as a weighted composite of individual rule scores.
     * Used for portfolio-level risk reporting and trend dashboards.
     */
    @Field("risk_score")
    private Integer riskScore;

    /**
     * evaluatedAt — UTC timestamp of when the BRE completed evaluation.
     * Used for SLA tracking (BRE turnaround time) and audit.
     */
    @Field("evaluated_at")
    private Instant evaluatedAt;

    /**
     * evaluatorVersion — the version string of the BRE engine that produced this result.
     * Example: "1.0.0". Critical for debugging: if a rule change causes unexpected
     * decisions, we can identify all decisions made by that evaluator version.
     */
    @Field("evaluator_version")
    private String evaluatorVersion;

    /**
     * ruleOutcomes — a brief list of which rules passed and which failed.
     * Displayed on the loan officer's review screen so they can understand
     * WHY the BRE produced this decision without reading the full DecisionLog.
     *
     * Why a List here and also in DecisionLog?
     * DecisionLog has the FULL verbose record (used for audits).
     * This embedded list is a TRIMMED summary (used for live UI display).
     */
    @Field("rule_outcomes")
    private List<RuleOutcomeSummary> ruleOutcomes;

    /**
     * overallComment — a brief auto-generated human-readable summary of the decision.
     * Example: "Application rejected: credit score (580) below minimum threshold (650)."
     * Generated by the BRE engine, not typed manually.
     */
    @Field("overall_comment")
    private String overallComment;

    // ── Inner class: RuleOutcomeSummary ──────────────────────────────────────
    // A static inner class is used instead of a top-level class because
    // RuleOutcomeSummary is ONLY ever used inside DecisionResult — it has no
    // independent meaning and doesn't need its own file.

    /**
     * RuleOutcomeSummary — one row in the rule-by-rule evaluation table.
     * Tells the loan officer: rule name, passed/failed, and the reason.
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class RuleOutcomeSummary {

        /** The human-readable name of the rule (e.g., "Minimum Credit Score Check") */
        @Field("rule_name")
        private String ruleName;

        /** true = this rule passed; false = this rule caused rejection */
        @Field("passed")
        private boolean passed;

        /**
         * reason — explains the outcome in plain language.
         * Examples:
         *   passed=true:  "Credit score 720 ≥ minimum threshold 650. PASS."
         *   passed=false: "DTI ratio 52% exceeds maximum allowed 40%. FAIL."
         */
        @Field("reason")
        private String reason;

        /** The actual value evaluated (e.g., the applicant's credit score = 580) */
        @Field("actual_value")
        private String actualValue;

        /** The threshold the rule required (e.g., minimum score = 650) */
        @Field("threshold_value")
        private String thresholdValue;
    }
}
