// frontend/src/app/core/models/application.models.ts

/*
 * TYPESCRIPT INTERFACES:
 * These define the exact shape of the data we send to and receive from the backend.
 * This is like a contract between the frontend and backend, preventing us from sending
 * a "string" when the backend expects a "number".
 */

// Represents the personal details of the person applying for the loan.
export interface ApplicantDto {
  // The person's full legal name.
  name: string;
  // Their contact email address.
  email: string;
  // Their contact phone number.
  phone: string;
  // Date of birth (expected in YYYY-MM-DD format).
  dob: string;
  // Their physical home address.
  address: string;
  // Their government-issued ID number (SSN, Passport, etc.).
  nationalId: string;
}

// Represents the data created when an applicant is successfully saved in the backend.
export interface ApplicantResponseDto extends ApplicantDto {
  // The unique database ID generated by the backend for this applicant.
  id: string;
}

// Represents the specific details of the loan they want.
export interface ApplicationDto {
  // The ID of the applicant requesting the loan.
  applicantId: string;
  // How much money they want to borrow.
  amount: number;
  // How long they want to take to pay it back (e.g., in months).
  tenureMonths: number;
  // What they plan to use the money for (e.g., "Home Improvement", "Debt Consolidation").
  purpose: string;
  // Their declared monthly income (used to calculate ability to repay).
  monthlyIncome: number;
}

// Represents the full application record returned from the backend.
export interface ApplicationResponseDto extends ApplicationDto {
  // The unique database ID for the loan application.
  id: string;
  // The current lifecycle stage of the application (e.g., SUBMITTED, UNDER_REVIEW, APPROVED, REJECTED).
  status: string;
  // The decision details if the Business Rule Engine has evaluated this application.
  decision?: DecisionResultDto;
}

// Represents the outcome of a single rule in the Business Rule Engine.
export interface RuleResultDto {
  // Internal name of the rule (e.g., "DebtToIncomeRatioRule").
  ruleName: string;
  // Whether they passed this specific check.
  passed: boolean;
  // Technical reason for the pass/fail from the backend.
  reason: string;
}

// Represents the final decision from the Business Rule Engine.
export interface DecisionResultDto {
  // Final yes/no on whether they get the loan.
  approved: boolean;
  // Calculated risk score from 0 to 100.
  riskScore: number;
  // The breakdown of every rule that was evaluated.
  ruleResults: RuleResultDto[];
}
